require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '13.0'

target 'Aminah' do
  # React Native Maps dependencies
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

#React native Permisions 
permissions_path = '../node_modules/react-native-permissions/ios'

pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
 # add next line
 pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
   
pod 'Firebase', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true

pod 'react-native-appsflyer',
:path => '../node_modules/react-native-appsflyer'


  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'AminahTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  
  post_install do |installer|
    react_native_post_install(installer)
      ################### ADD THE FOLLOWING #########################
      # Run the React-Native post install
           
          # Get the development team id from the main project
          # dev_team_id = ""
          # project = installer.aggregate_targets[0].user_project
          # project.targets.each do |target|
          #   target.build_configurations.each do |config|
          #     if dev_team_id.empty? and !config.build_settings['DEVELOPMENT_TEAM'].nil?
          #       dev_team_id = config.build_settings['DEVELOPMENT_TEAM']
          #     end
          #   end
          # end

            # Reconfigure the pods, update deployment target and signing settings
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                if target.respond_to?(:product_type) and target.product_type == 'com.apple.product-type.bundle'
                  config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
                end if
                
  
                config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
              end
            end
      ########
  end

end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end